name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/raphaelhuerzele/450-tictactest-mvk:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew clean build --no-daemon
